import { User } from '../../user/user.entity';

export const UserSeed: User[] = [
  {
    id: 1,
    email: 'george.bluth@yahoo.com.my',
    firstName: 'George',
    lastName: 'Bluth',
    photo: 'https://reqres.in/img/faces/1-image.jpg',
  },
  {
    id: 2,
    email: 'janet.weaver@gmail.com',
    firstName: 'Janet',
    lastName: 'Weaver',
    photo: 'https://reqres.in/img/faces/2-image.jpg',
  },
  {
    id: 3,
    email: 'emma.wong@mailsaur.net',
    firstName: 'Emma',
    lastName: 'Wong',
    photo: 'https://reqres.in/img/faces/3-image.jpg',
  },
  {
    id: 4,
    email: 'eve.holt@googlemail.co.uk',
    firstName: 'Eve',
    lastName: 'Holt',
    photo: 'https://reqres.in/img/faces/4-image.jpg',
  },
  {
    id: 5,
    email: 'charles.morris@grabmart.com.my',
    firstName: 'Charles',
    lastName: 'Morris',
    photo: 'https://reqres.in/img/faces/5-image.jpg',
  },
  {
    id: 6,
    email: 'tracey.remos@gmail.com',
    firstName: 'Tracey',
    lastName: 'Ramos',
    photo: 'https://reqres.in/img/faces/6-image.jpg',
  },
  {
    id: 7,
    email: 'michael.jackson@sony.com',
    firstName: 'Michael',
    lastName: 'Jackson',
    photo: 'https://reqres.in/img/faces/7-image.jpg',
  },
  {
    id: 8,
    email: 'gwen.ferguson@bluebottle.com',
    firstName: 'Gwendolyn',
    lastName: 'Ferguson',
    photo: 'https://reqres.in/img/faces/8-image.jpg',
  },
  {
    id: 9,
    email: 'tobias.funke@docomo.co.jp',
    firstName: 'Tobias',
    lastName: 'Funke',
    photo: 'https://reqres.in/img/faces/9-image.jpg',
  },
  {
    id: 10,
    email: 'byron.fields@gmail.com',
    firstName: 'Byron',
    lastName: 'Fields',
    photo: 'https://reqres.in/img/faces/10-image.jpg',
  },
  {
    id: 11,
    email: 'george.edwards@yahoo.co.id',
    firstName: 'George',
    lastName: 'Edwards',
    photo: 'https://reqres.in/img/faces/11-image.jpg',
  },
  {
    id: 12,
    email: 'rachel.winterson@altavista.com',
    firstName: 'Rachel',
    lastName: 'Winterson',
    photo: 'https://reqres.in/img/faces/12-image.jpg',
  },
];
